term.clear()
term.setCursorPos(1, 1)
term.setTextColor(colors.yellow)
print("CraftOS 1.9")
term.setBackgroundColor(colors.black)
term.blit("> ls /", "400000", "ffffff")
term.setTextColor(colors.red)
print("\nYour files are gone. hehe :)")
term.blit("> ls /rom", "400000000", "fffffffff")
term.setTextColor(colors.red)
print("\nYour files are gone. hehe :)")
term.blit("> cash", "400000", "ffffff")
term.setTextColor(colors.red)
print("\nYour files are gone. hehe :)")
term.blit("> Terminated", "40eeeeeeeeee", "ffffffffffff")
term.setTextColor(colors.yellow)
print("\nGoodbye")

while os.pullEvent() do end